In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt 
from collections import defaultdict

In [4]:
df2 = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\training_data\entire_odds_stats_2026-03-09.csv')
df1 = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\training_data\entire_odds_stats_2026-03-08.csv')
print(df1.shape, df2.shape)

(8112, 297) (8112, 297)

In [5]:
df1.tail()[['date', 'fighter_red', 'fighter_blue', 'elo_red']]

            date     fighter_red      fighter_blue      elo_red
8107  2026-02-21  ramiz brahimaj  punahele soriano  1551.904810
8108  2026-02-21     alden coria       luis gurule  1526.792785
8109  2026-02-21         dan ige  melquizael costa  1548.124920
8110  2026-02-21   nora cornolle  joselyne edwards  1522.560905
8111  2026-02-21  jordan leavitt  yadier del valle  1537.800959

In [6]:
df2.tail()[['date', 'fighter_red', 'fighter_blue', 'elo_red']]

            date     fighter_red      fighter_blue      elo_red
8107  2026-02-21  ramiz brahimaj  punahele soriano  1551.904810
8108  2026-02-21     alden coria       luis gurule  1526.792785
8109  2026-02-21         dan ige  melquizael costa  1548.124920
8110  2026-02-21   nora cornolle  joselyne edwards  1522.560905
8111  2026-02-21  jordan leavitt  yadier del valle  1537.800959

In [10]:
pd.set_option('display.max_rows', None)

In [13]:
df_rolling = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\features_test_files\ufc_new_rolling.csv')
df_rolling.isna().sum()

C:\Users\jcmar\AppData\Local\Temp\ipykernel_33732\565577325.py:1: DtypeWarning: Columns (86,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rolling = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\features_test_files\ufc_new_rolling.csv')

td_defense_pct_red                       796
td_total_attempted_against_red           791
td_total_landed_against_red              791
td_defense_pct_blue                     1638
td_total_attempted_against_blue         1634
td_total_landed_against_blue            1634
sig_str_defense_pct_red                  796
sig_str_total_attempted_against_red      791
sig_str_total_landed_against_red         791
sig_str_defense_pct_blue                1638
sig_str_total_attempted_against_blue    1634
sig_str_total_landed_against_blue       1634
td_accuracy_pct_red                      796
td_accuracy_pct_blue                    1638
sig_str_accuracy_pct_red                 796
sig_str_accuracy_pct_blue               1638
kd_pm_red                                791
kd_total_red                             791
kd_pm_blue                              1634
kd_total_blue                           1634
sig_str_landed_pm_red                    791
sig_str_landed_total_red                 791
sig_str_landed_pm_blue                  1634
sig_str_landed_total_blue               1634
sig_str_absorbed_pm_red                  791
sig_str_absorbed_total_red               791
sig_str_absorbed_pm_blue                1634
sig_str_absorbed_total_blue             1634
sig_str_attempted_pm_red                 791
sig_str_attempted_total_red              791
sig_str_attempted_pm_blue               1634
sig_str_attempted_total_blue            1634
leg_str_pm_red                           791
leg_str_total_red                        791
leg_str_pm_blue                         1634
leg_str_total_blue                      1634
head_str_pm_red                          791
head_str_total_red                       791
head_str_pm_blue                        1634
head_str_total_blue                     1634
body_str_pm_red                          791
body_str_total_red                       791
body_str_pm_blue                        1634
body_str_total_blue                     1634
clinch_str_pm_red                        791
clinch_str_total_red                     791
clinch_str_pm_blue                      1634
clinch_str_total_blue                   1634
td_landed_pm_red                         791
td_landed_total_red                      791
td_landed_pm_blue                       1634
td_landed_total_blue                    1634
td_attempted_pm_red                      791
td_attempted_total_red                   791
td_attempted_pm_blue                    1634
td_attempted_total_blue                 1634
td_defended_pm_red                       791
td_defended_total_red                    791
td_defended_pm_blue                     1634
td_defended_total_blue                  1634
control_pm_red                           791
control_total_red                        791
control_pm_blue                         1634
control_total_blue                      1634
sub_att_pm_red                           791
sub_att_total_red                        791
sub_att_pm_blue                         1634
sub_att_total_blue                      1634
reverse_pm_red                           791
reverse_total_red                        791
reverse_pm_blue                         1634
reverse_total_blue                      1634
total_fight_time_red                       0
total_fight_time_blue                      0
age_red                                    3
age_blue                                  21
height_red                                 4
height_blue                                3
reach_red                                157
reach_blue                               554
date                                       0
event_location                             0
weight_class                               0
title_fight                                0
performance_bonus_winner                  78
fight_otn_bonus                           78
method                                    78
winner                                     0
winner_name                               78
fighter_red                                0
fighter_blue                               0
ratio_td_red                             953
ratio_td_blue                           1691
ratio_control_red                        953
ratio_control_blue                      1691
ratio_sig_str_red                        953
ratio_sig_str_blue                      1691
adjusted_sig_str_red                    1539
adjusted_sig_str_blue                   2394
adjusted_td_red                         1539
adjusted_td_blue                        2394
ratio_td_diff                           1970
ratio_control_diff                      1970
ratio_sigstrike_diff                    1970
dtype: int64

In [18]:
def find_duplicates(df):
    duplicates = (
        df[df.duplicated(
            subset=['fighter_red', 'fighter_blue', 'date'],
            keep=False
        )]
        .sort_values(['date', 'fighter_red', 'fighter_blue'])
        .reset_index(drop=True)
    )
    print(duplicates[['fighter_red', 'fighter_blue']])

find_duplicates(df_rolling)

Empty DataFrame
Columns: [fighter_red, fighter_blue]
Index: []

In [15]:
df_pre_fight = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\features_test_files\ufc_single_event_features.csv')
df_pre_fight.isna().sum()

title_fight                   0
event_name                    0
event_date                    0
event_location                0
fight_url                     0
weight_class                  0
method                        0
round                         0
fight_time                    0
performance_bonus_winner      0
fight_otn_bonus               0
winner                        0
fighter_red                   0
fighter_blue                  0
record_red                    0
record_blue                   0
dob_red                       0
dob_blue                      0
height_red                    2
height_blue                   2
reach_red                   155
reach_blue                  553
stance_red                   14
stance_blue                  35
kd_red                        0
kd_blue                       0
sig_str_red                   0
sig_str_blue                  0
sig_str_percent_red           0
sig_str_percent_blue          0
td_red                        0
td_blue                       0
td_pct_red                    0
td_pct_blue                   0
clinch_red                    0
clinch_blue                   0
ground_red                    0
ground_blue                   0
sub_att_red                   0
sub_att_blue                  0
rev_red                       0
rev_blue                      0
ctrl_red                      0
ctrl_blue                     0
head_red                      0
head_blue                     0
body_red                      0
body_blue                     0
leg_red                       0
leg_blue                      0
distance_red                  0
distance_blue                 0
total_strikes_red             0
total_strikes_blue            0
event_age                     0
date                          0
fight_minutes                 0
wins_red                      0
losses_red                    0
age_red                       3
wins_blue                     0
losses_blue                   0
age_blue                     21
td_landed_red                 0
td_attempted_red              0
td_defended_red               0
control_red                   0
reverse_red                   0
td_landed_blue                0
td_attempted_blue             0
td_defended_blue              0
control_blue                  0
reverse_blue                  0
sig_str_landed_red            0
sig_str_attempted_red         0
sig_str_absorbed_red          0
leg_str_red                   0
head_str_red                  0
body_str_red                  0
clinch_str_red                0
sig_str_landed_blue           0
sig_str_attempted_blue        0
sig_str_absorbed_blue         0
leg_str_blue                  0
head_str_blue                 0
body_str_blue                 0
clinch_str_blue               0
dtype: int64

In [19]:
find_duplicates(df_pre_fight)

Empty DataFrame
Columns: [fighter_red, fighter_blue]
Index: []

In [21]:
stats_history = pd.read_csv( r'C:\Users\jcmar\my_files\SportsBetting\Data\scraped_data_main\stats_history_2026-02-26.csv')
stats_history.isna().sum()

Unnamed: 0                   0
title_fight                  0
event_name                   0
event_date                   0
event_location               0
fight_url                    0
weight_class                 0
method                       0
round                        0
fight_time                   0
performance_bonus_winner     0
fight_otn_bonus              0
winner                       0
fighter_red                  0
fighter_blue                 0
record_red                   0
record_blue                  0
dob_red                      0
dob_blue                     0
height_red                   0
height_blue                  0
reach_red                    0
reach_blue                   0
stance_red                  14
stance_blue                 36
kd_red                       0
kd_blue                      0
sig_str_red                  0
sig_str_blue                 0
sig_str_percent_red          0
sig_str_percent_blue         0
td_red                       0
td_blue                      0
td_pct_red                   0
td_pct_blue                  0
clinch_red                   0
clinch_blue                  0
ground_red                   0
ground_blue                  0
sub_att_red                  0
sub_att_blue                 0
rev_red                      0
rev_blue                     0
ctrl_red                     0
ctrl_blue                    0
head_red                     0
head_blue                    0
body_red                     0
body_blue                    0
leg_red                      0
leg_blue                     0
distance_red                 0
distance_blue                0
total_strikes_red            0
total_strikes_blue           0
dtype: int64

In [22]:
df_odds_feats = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\features_test_files\all_odds_features.csv')
df_odds_feats.isna().sum()

blue_fighter                    0
open_blue                       0
close1_blue                     0
close2_blue                     0
red_fighter                     0
open_red                        0
close1_red                      0
close2_red                      0
event_date                     20
og_blue_name                    0
og_red_fighter                348
Unnamed: 0                   8294
dec_open_red                    0
dec_close1_red                  0
dec_close2_red                  0
dec_open_blue                   0
dec_close1_blue                 0
dec_close2_blue                 0
dec_fair_open_red               0
dec_fair_open_blue              0
proba_fair_open_red             0
proba_fair_open_blue            0
pimp_open_red                   0
pimp_open_blue                  0
dec_fair_close1_red             0
dec_fair_close1_blue            0
proba_fair_close1_red           0
proba_fair_close1_blue          0
pimp_close1_red                 0
pimp_close1_blue                0
dec_fair_close2_red             0
dec_fair_close2_blue            0
proba_fair_close2_red           0
proba_fair_close2_blue          0
pimp_close2_red                 0
pimp_close2_blue                0
juice_open_red                  0
juice_close1_red                0
juice_close2_red                0
juice_open_blue                 0
juice_close1_blue               0
juice_close2_blue               0
vegas_acc_open                  0
vegas_acc_close1                0
vegas_acc_close2                0
proba_fair_open_diff            0
proba_fair_close1_diff          0
proba_fair_close2_diff          0
line_movement_close1_red        0
line_movement_close1_blue       0
line_movement_close2_red        0
line_movement_close2_blue       0
red_ud_to_fav_close1            0
red_ud_to_fav_close2            0
red_stayed_fav_close1           0
red_stayed_fav_close2           0
red_fav_to_ud_close1            0
red_fav_to_ud_close2            0
red_stayed_dog_close1           0
red_stayed_dog_close2           0
blue_ud_to_fav_close1           0
blue_ud_to_fav_close2           0
blue_stayed_fav_close1          0
blue_stayed_fav_close2          0
blue_fav_to_ud_close1           0
blue_fav_to_ud_close2           0
blue_stayed_dog_close1          0
blue_stayed_dog_close2          0
dtype: int64

In [23]:
df_stats_odds = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\features_test_files\stats_odds_merged.csv')
df_stats_odds.isna().sum()

C:\Users\jcmar\AppData\Local\Temp\ipykernel_33732\453694502.py:1: DtypeWarning: Columns (86,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df_stats_odds = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\Data\features_test_files\stats_odds_merged.csv')

td_defense_pct_red                       796
td_total_attempted_against_red           791
td_total_landed_against_red              791
td_defense_pct_blue                     1638
td_total_attempted_against_blue         1634
td_total_landed_against_blue            1634
sig_str_defense_pct_red                  796
sig_str_total_attempted_against_red      791
sig_str_total_landed_against_red         791
sig_str_defense_pct_blue                1638
sig_str_total_attempted_against_blue    1634
sig_str_total_landed_against_blue       1634
td_accuracy_pct_red                      796
td_accuracy_pct_blue                    1638
sig_str_accuracy_pct_red                 796
sig_str_accuracy_pct_blue               1638
kd_pm_red                                791
kd_total_red                             791
kd_pm_blue                              1634
kd_total_blue                           1634
sig_str_landed_pm_red                    791
sig_str_landed_total_red                 791
sig_str_landed_pm_blue                  1634
sig_str_landed_total_blue               1634
sig_str_absorbed_pm_red                  791
sig_str_absorbed_total_red               791
sig_str_absorbed_pm_blue                1634
sig_str_absorbed_total_blue             1634
sig_str_attempted_pm_red                 791
sig_str_attempted_total_red              791
sig_str_attempted_pm_blue               1634
sig_str_attempted_total_blue            1634
leg_str_pm_red                           791
leg_str_total_red                        791
leg_str_pm_blue                         1634
leg_str_total_blue                      1634
head_str_pm_red                          791
head_str_total_red                       791
head_str_pm_blue                        1634
head_str_total_blue                     1634
body_str_pm_red                          791
body_str_total_red                       791
body_str_pm_blue                        1634
body_str_total_blue                     1634
clinch_str_pm_red                        791
clinch_str_total_red                     791
clinch_str_pm_blue                      1634
clinch_str_total_blue                   1634
td_landed_pm_red                         791
td_landed_total_red                      791
td_landed_pm_blue                       1634
td_landed_total_blue                    1634
td_attempted_pm_red                      791
td_attempted_total_red                   791
td_attempted_pm_blue                    1634
td_attempted_total_blue                 1634
td_defended_pm_red                       791
td_defended_total_red                    791
td_defended_pm_blue                     1634
td_defended_total_blue                  1634
control_pm_red                           791
control_total_red                        791
control_pm_blue                         1634
control_total_blue                      1634
sub_att_pm_red                           791
sub_att_total_red                        791
sub_att_pm_blue                         1634
sub_att_total_blue                      1634
reverse_pm_red                           791
reverse_total_red                        791
reverse_pm_blue                         1634
reverse_total_blue                      1634
total_fight_time_red                       0
total_fight_time_blue                      0
age_red                                    0
age_blue                                   0
height_red                                 0
height_blue                                0
reach_red                                  0
reach_blue                                 0
date                                       0
event_location                             0
weight_class                               0
title_fight                                0
performance_bonus_winner                  78
fight_otn_bonus                           78
method                                    78
winner                                     0
winner_name                               78
ratio_td_red                             953
ratio_td_blue                           1691
ratio_control_red                        953
ratio_control_blue                      1691
ratio_sig_str_red                        953
ratio_sig_str_blue                      1691
adjusted_sig_str_red                    1539
adjusted_sig_str_blue                   2394
adjusted_td_red                         1539
adjusted_td_blue                        2394
ratio_td_diff                           1970
ratio_control_diff                      1970
ratio_sigstrike_diff                    1970
kd_total_diff                           1970
kd_pm_diff                              1970
sig_str_landed_total_diff               1970
sig_str_landed_pm_diff                  1970
sig_str_absorbed_total_diff             1970
sig_str_absorbed_pm_diff                1970
sig_str_attempted_total_diff            1970
sig_str_attempted_pm_diff               1970
leg_str_total_diff                      1970
leg_str_pm_diff                         1970
head_str_total_diff                     1970
head_str_pm_diff                        1970
body_str_total_diff                     1970
body_str_pm_diff                        1970
clinch_str_total_diff                   1970
clinch_str_pm_diff                      1970
td_landed_total_diff                    1970
td_landed_pm_diff                       1970
td_attempted_total_diff                 1970
td_attempted_pm_diff                    1970
control_total_diff                      1970
control_pm_diff                         1970
sub_att_total_diff                      1970
sub_att_pm_diff                         1970
reverse_total_diff                      1970
reverse_pm_diff                         1970
age_diff                                  24
height_diff                                7
reach_diff                               680
sig_str_defense_pct_diff                1972
sig_str_accuracy_pct_diff               1972
td_accuracy_pct_diff                    1972
td_defense_pct_diff                     1972
opp_age_red                              791
opp_age_blue                            1634
opp_reach_red                            791
opp_reach_blue                          1634
avg_fight_min_red                        791
avg_fight_min_blue                      1634
avg_fight_min_diff                      1970
total_bonus_red                          791
total_bonus_blue                        1634
total_bonus_diff                        1970
elo_red                                    0
elo_blue                                   0
elo_red_proba                              0
elo_blue_proba                             0
elo_diff                                   0
elo_pred                                   0
glicko_red                                 0
glicko_blue                                0
glicko_rd_red                              0
glicko_rd_blue                             0
glicko_proba_red                           0
glicko_proba_blue                          0
glicko_diff                                0
glicko_pred                                0
rating_agree                               0
math_red                                   0
math_blue                                  0
months_since_red                         791
months_since_blue                       1634
months_since_diff                       1970
win_streak_red                             0
lose_streak_red                            0
win_streak_blue                            0
lose_streak_blue                           0
win_pct_red                                0
win_pct_blue                               0
num_fights_red                             0
num_fights_blue                            0
num_wins_red                               0
num_wins_blue                              0
num_losses_red                             0
num_losses_blue                            0
num_fights_diff                            0
win_streak_diff                            0
lose_streak_diff                           0
wins_diff                                  0
losses_diff                                0
win_pct_diff                               0
decision_wins_red                          0
ko_wins_red                                0
sub_wins_red                               0
decision_wins_blue                         0
ko_wins_blue                               0
sub_wins_blue                              0
decision_wins_diff                         0
ko_wins_diff                               0
sub_wins_diff                              0
decision_losses_red                        0
ko_losses_red                              0
sub_losses_red                             0
decision_losses_blue                       0
ko_losses_blue                             0
sub_losses_blue                            0
decision_losses_diff                       0
ko_losses_diff                             0
sub_losses_diff                            0
ko_pct_red                                 0
dec_pct_red                                0
sub_pct_red                                0
ko_pct_blue                                0
dec_pct_blue                               0
sub_pct_blue                               0
ko_pct_diff                                0
dec_pct_diff                               0
sub_pct_diff                               0
womens_fight                               0
red_title_fights                           0
blue_title_fights                          0
red_title_wins                             0
blue_title_wins                            0
red_title_losses                           0
blue_title_losses                          0
red_title_win_pct                          0
blue_title_win_pct                         0
event_age                                  0
fighter_red                                0
fighter_blue                               0
red_fighter_stats                          0
blue_fighter_stats                         0
open_blue                                988
close1_blue                              988
close2_blue                              988
open_red                                 988
close1_red                               988
close2_red                               988
event_date                               988
og_blue_name                             988
og_red_fighter                          1311
dec_open_red                             988
dec_close1_red                           988
dec_close2_red                           988
dec_open_blue                            988
dec_close1_blue                          988
dec_close2_blue                          988
dec_fair_open_red                        988
dec_fair_open_blue                       988
proba_fair_open_red                      988
proba_fair_open_blue                     988
pimp_open_red                            988
pimp_open_blue                           988
dec_fair_close1_red                      988
dec_fair_close1_blue                     988
proba_fair_close1_red                    988
proba_fair_close1_blue                   988
pimp_close1_red                          988
pimp_close1_blue                         988
dec_fair_close2_red                      988
dec_fair_close2_blue                     988
proba_fair_close2_red                    988
proba_fair_close2_blue                   988
pimp_close2_red                          988
pimp_close2_blue                         988
juice_open_red                           988
juice_close1_red                         988
juice_close2_red                         988
juice_open_blue                          988
juice_close1_blue                        988
juice_close2_blue                        988
vegas_acc_open                           988
vegas_acc_close1                         988
vegas_acc_close2                         988
proba_fair_open_diff                     988
proba_fair_close1_diff                   988
proba_fair_close2_diff                   988
line_movement_close1_red                 988
line_movement_close1_blue                988
line_movement_close2_red                 988
line_movement_close2_blue                988
red_ud_to_fav_close1                     988
red_ud_to_fav_close2                     988
red_stayed_fav_close1                    988
red_stayed_fav_close2                    988
red_fav_to_ud_close1                     988
red_fav_to_ud_close2                     988
red_stayed_dog_close1                    988
red_stayed_dog_close2                    988
blue_ud_to_fav_close1                    988
blue_ud_to_fav_close2                    988
blue_stayed_fav_close1                   988
blue_stayed_fav_close2                   988
blue_fav_to_ud_close1                    988
blue_fav_to_ud_close2                    988
blue_stayed_dog_close1                   988
blue_stayed_dog_close2                   988
red_fighter_odds                         988
blue_fighter_odds                        988
dtype: int64

In [25]:
duplicates = df_stats_odds.groupby(['fighter_red', 'fighter_blue','date']).size().reset_index(name='count').query('count>1')
print(duplicates)

Empty DataFrame
Columns: [fighter_red, fighter_blue, date, count]
Index: []

In [27]:
df_combined = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\data\features_test_files\new_combined.csv')
df_combined.isna().sum()

C:\Users\jcmar\AppData\Local\Temp\ipykernel_33732\758810105.py:1: DtypeWarning: Columns (86,88) have mixed types. Specify dtype option on import or set low_memory=False.
  df_combined = pd.read_csv(r'C:\Users\jcmar\my_files\SportsBetting\data\features_test_files\new_combined.csv')

td_defense_pct_red                       796
td_total_attempted_against_red           791
td_total_landed_against_red              791
td_defense_pct_blue                     1638
td_total_attempted_against_blue         1634
td_total_landed_against_blue            1634
sig_str_defense_pct_red                  796
sig_str_total_attempted_against_red      791
sig_str_total_landed_against_red         791
sig_str_defense_pct_blue                1638
sig_str_total_attempted_against_blue    1634
sig_str_total_landed_against_blue       1634
td_accuracy_pct_red                      796
td_accuracy_pct_blue                    1638
sig_str_accuracy_pct_red                 796
sig_str_accuracy_pct_blue               1638
kd_pm_red                                791
kd_total_red                             791
kd_pm_blue                              1634
kd_total_blue                           1634
sig_str_landed_pm_red                    791
sig_str_landed_total_red                 791
sig_str_landed_pm_blue                  1634
sig_str_landed_total_blue               1634
sig_str_absorbed_pm_red                  791
sig_str_absorbed_total_red               791
sig_str_absorbed_pm_blue                1634
sig_str_absorbed_total_blue             1634
sig_str_attempted_pm_red                 791
sig_str_attempted_total_red              791
sig_str_attempted_pm_blue               1634
sig_str_attempted_total_blue            1634
leg_str_pm_red                           791
leg_str_total_red                        791
leg_str_pm_blue                         1634
leg_str_total_blue                      1634
head_str_pm_red                          791
head_str_total_red                       791
head_str_pm_blue                        1634
head_str_total_blue                     1634
body_str_pm_red                          791
body_str_total_red                       791
body_str_pm_blue                        1634
body_str_total_blue                     1634
clinch_str_pm_red                        791
clinch_str_total_red                     791
clinch_str_pm_blue                      1634
clinch_str_total_blue                   1634
td_landed_pm_red                         791
td_landed_total_red                      791
td_landed_pm_blue                       1634
td_landed_total_blue                    1634
td_attempted_pm_red                      791
td_attempted_total_red                   791
td_attempted_pm_blue                    1634
td_attempted_total_blue                 1634
td_defended_pm_red                       791
td_defended_total_red                    791
td_defended_pm_blue                     1634
td_defended_total_blue                  1634
control_pm_red                           791
control_total_red                        791
control_pm_blue                         1634
control_total_blue                      1634
sub_att_pm_red                           791
sub_att_total_red                        791
sub_att_pm_blue                         1634
sub_att_total_blue                      1634
reverse_pm_red                           791
reverse_total_red                        791
reverse_pm_blue                         1634
reverse_total_blue                      1634
total_fight_time_red                       0
total_fight_time_blue                      0
age_red                                    0
age_blue                                   0
height_red                                 0
height_blue                                0
reach_red                                  0
reach_blue                                 0
date                                       0
event_location                             0
weight_class                               0
title_fight                                0
performance_bonus_winner                  78
fight_otn_bonus                           78
method                                    78
winner                                     0
winner_name                               78
fighter_red                                0
fighter_blue                               0
ratio_td_red                             953
ratio_td_blue                           1691
ratio_control_red                        953
ratio_control_blue                      1691
ratio_sig_str_red                        953
ratio_sig_str_blue                      1691
adjusted_sig_str_red                    1539
adjusted_sig_str_blue                   2394
adjusted_td_red                         1539
adjusted_td_blue                        2394
ratio_td_diff                           1970
ratio_control_diff                      1970
ratio_sigstrike_diff                    1970
kd_total_diff                           1970
kd_pm_diff                              1970
sig_str_landed_total_diff               1970
sig_str_landed_pm_diff                  1970
sig_str_absorbed_total_diff             1970
sig_str_absorbed_pm_diff                1970
sig_str_attempted_total_diff            1970
sig_str_attempted_pm_diff               1970
leg_str_total_diff                      1970
leg_str_pm_diff                         1970
head_str_total_diff                     1970
head_str_pm_diff                        1970
body_str_total_diff                     1970
body_str_pm_diff                        1970
clinch_str_total_diff                   1970
clinch_str_pm_diff                      1970
td_landed_total_diff                    1970
td_landed_pm_diff                       1970
td_attempted_total_diff                 1970
td_attempted_pm_diff                    1970
control_total_diff                      1970
control_pm_diff                         1970
sub_att_total_diff                      1970
sub_att_pm_diff                         1970
reverse_total_diff                      1970
reverse_pm_diff                         1970
age_diff                                  24
height_diff                                7
reach_diff                               680
sig_str_defense_pct_diff                1972
sig_str_accuracy_pct_diff               1972
td_accuracy_pct_diff                    1972
td_defense_pct_diff                     1972
opp_age_red                              791
opp_age_blue                            1634
opp_reach_red                            791
opp_reach_blue                          1634
avg_fight_min_red                        791
avg_fight_min_blue                      1634
avg_fight_min_diff                      1970
total_bonus_red                          791
total_bonus_blue                        1634
total_bonus_diff                        1970
elo_red                                    0
elo_blue                                   0
elo_red_proba                              0
elo_blue_proba                             0
elo_diff                                   0
elo_pred                                   0
glicko_red                                 0
glicko_blue                                0
glicko_rd_red                              0
glicko_rd_blue                             0
glicko_proba_red                           0
glicko_proba_blue                          0
glicko_diff                                0
glicko_pred                                0
rating_agree                               0
math_red                                   0
math_blue                                  0
months_since_red                         791
months_since_blue                       1634
months_since_diff                       1970
win_streak_red                             0
lose_streak_red                            0
win_streak_blue                            0
lose_streak_blue                           0
win_pct_red                                0
win_pct_blue                               0
num_fights_red                             0
num_fights_blue                            0
num_wins_red                               0
num_wins_blue                              0
num_losses_red                             0
num_losses_blue                            0
num_fights_diff                            0
win_streak_diff                            0
lose_streak_diff                           0
wins_diff                                  0
losses_diff                                0
win_pct_diff                               0
decision_wins_red                          0
ko_wins_red                                0
sub_wins_red                               0
decision_wins_blue                         0
ko_wins_blue                               0
sub_wins_blue                              0
decision_wins_diff                         0
ko_wins_diff                               0
sub_wins_diff                              0
decision_losses_red                        0
ko_losses_red                              0
sub_losses_red                             0
decision_losses_blue                       0
ko_losses_blue                             0
sub_losses_blue                            0
decision_losses_diff                       0
ko_losses_diff                             0
sub_losses_diff                            0
ko_pct_red                                 0
dec_pct_red                                0
sub_pct_red                                0
ko_pct_blue                                0
dec_pct_blue                               0
sub_pct_blue                               0
ko_pct_diff                                0
dec_pct_diff                               0
sub_pct_diff                               0
womens_fight                               0
red_title_fights                           0
blue_title_fights                          0
red_title_wins                             0
blue_title_wins                            0
red_title_losses                           0
blue_title_losses                          0
red_title_win_pct                          0
blue_title_win_pct                         0
event_age                                  0
dtype: int64